services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SIBEC
      MYSQL_USER: sibec_user
      MYSQL_PASSWORD: bRtMqyNi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
      driver: local

networks:
  default:
    driver: bridge